accounts/urls.py
from django.urls import path , include 
from . import views
from .views import *
from .models import * 
app_name = 'accounts'

urlpatterns = [
    path('signup/' , views.signup , name = "signup" ) ,
    path('profile/' , views.profile , name = "profile" ) ,
    path('profile/edit' , views.profile_edit , name = "profile_edit" ) ,
    
]

contact/urls.py
from django.urls import path , include 
from . import views
from .views import *
from .models import * 
app_name = "job" 

urlpatterns = [
    path('' , views.send_message , name = "contact" ) ,
]

job/urls.py
from django.urls import path , include 
from . import views
from .views import *
from .models import * 
app_name = "job" 

urlpatterns = [
    path('' , views.job_list , name = "job_list" ) ,
    path('add' , views.add_job , name = "add_job" ) ,
    path('<str:slug>' , views.job_detail , name = "job_detail" )
]

project/urls.py
from django.contrib import admin
from django.urls import path , include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace="accounts") ) ,
    path('admin/', admin.site.urls),
    path('job/' , include('job.urls',namespace="job") ) , 
    path('contact-us/' , include('contact.urls',namespace="contact") ) ,
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_delete
from django.contrib.auth.models import User
from django.dispatch import receiver

# Create your models here.

class City ( models.Model ) : 
    name = models.CharField( max_length = 50 )
    def __str__( self ) :
        return self.name 

class Profile ( models.Model ) :
    user = models.OneToOneField( User , on_delete = models.CASCADE ) 
    city = models.ForeignKey( 'city' , related_name = 'user_city' , on_delete = models.CASCADE , null = True , blank = True ) 
    phone_number = models.CharField( max_length = 15 ) 
    image = models.ImageField( upload_to = 'profile/' )
    def __str__( self ) :
        return str(self.user) 


@receiver( post_save , sender = User ) 
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create( user=instance )

blog/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

job/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
# Create your models here.

class Category ( models.Model ) : 
    name = models.CharField( max_length = 100 ) 
    def __str__( self ) :
        return self.name 
    
JOB_TYBE = (
    ('full_time' , 'full_time') , 
    ('part_time' , 'part_time') ,
)

def upload_image ( instance , filename ) :
    imagename , extension = filename.split(".") 
    return "jobs/%s.%s"%(instance.id ,extension)  

class Job ( models.Model ) :
    owner = models.ForeignKey( User , related_name = 'job_owner' , on_delete = models.CASCADE ) # type: ignore
    title = models.CharField( max_length = 100 ) 
    #location 
    job_tybe = models.CharField( max_length = 10 , choices = JOB_TYBE )
    discription = models.TextField( max_length = 1000 ) 
    published_it = models.DateTimeField( auto_now = True ) 
    vacansy  = models.IntegerField( default = 1 ) 
    salary  = models.IntegerField( default = 0 ) 
    expereince = models.IntegerField( default = 1 ) 
    category = models.ForeignKey( 'Category' , on_delete = models.CASCADE )
    img = models.ImageField( upload_to = upload_image ) 
    slug = models.SlugField( null = True , blank = True ) 
    def save( self , *args , **kwargs ) :
        self.slug = slugify(self.title)
        super( Job , self ).save( *args , **kwargs ) 
    def __str__( self ) :
        return self.title 

class apply ( models.Model ) :
    job = models.ForeignKey( Job , related_name = 'apply_job' , on_delete = models.CASCADE )
    name = models.CharField( max_length= 50 ) 
    email = models.EmailField( max_length = 100 ) 
    website = models.URLField() 
    cv = models.FileField( upload_to = 'apply/') 
    cover = models.TextField( max_length = 500 ) 
    created_At = models.DateTimeField( auto_now = True ) 

    def __str__( self ) :
        return self.name 
 

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from.models import *

class Signup(UserCreationForm):
       email = forms.EmailField(required=True)

       class Meta:
           model = User
           fields = ['username', 'email', 'password1', 'password2']

class UserForm ( forms.ModelForm ) : 
      class Meta : 
            model = User 
            fields = ['username' , 'first_name' , 'last_name' , 'email' ] 

class ProfileForm ( forms.ModelForm ) : 
      class Meta : 
            model = Profile 
            fields = ['city' , 'phone_number' , 'image' ] 

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from .forms import Signup 
from .models import*
from .models import Profile 
from .forms import UserForm , ProfileForm 
from django.urls import reverse 


# Create your views here.


def signup ( request ) :
   if request.method == "POST" :
      form = Signup( request.POST , request.FILES ) 
      if form.is_valid() : 
         form.save() 
         username = form.cleaned_data['username']        
         password = form.cleaned_data['password1'] 
         user = authenticate( username = username , password = password )  
         login( request , user ) 
         return redirect ('/accounts/profile') 

   else :
      form = Signup()  
      print(form.errors)

   return render ( request , "registration/signup.html", { 'form' : form } )

def profile ( request ) :
   profile = Profile.objects.get( user = request.user )
   return render( request ,"accounts/profile.html",{ 'profile' : profile })

def profile_edit ( request ) :
   profile = Profile.objects.get( user = request.user )
   
   if request.method == 'POST' :
      userform = UserForm( request.POST , instance = request.user ) 
      profileform = ProfileForm( request.POST , request.FILES , instance = profile )
      if userform.is_valid() and profileform.is_valid() :
         userform.save() 
         x = profileform.save( commit = False )
         x.user = request.user 
         x.save() 
         return redirect( reverse('accounts:profile') )
   else : 
      userform = UserForm( instance = request.user ) 
      profileform = ProfileForm( instance = profile ) 
   
   return render( request , "accounts/profile_edit.html" , { 'userform' : userform , 'profileform' : profileform } ) 

blog/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

def send_message(request ) : 
 pass

home/views.py
from django.shortcuts import render

# Create your views here.

job/views.py
from django.shortcuts import redirect, render
from django.urls import reverse 
from .models import * 
from django.core.paginator import Paginator
from .form import Apply_form , Add_job
from django.contrib.auth.decorators import login_required
# Create your views here.

def job_list ( request ) : 
    data = Job.objects.all() 

    paginator = Paginator(data, 1)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        'job' : page_obj , 
    } 
    return render( request , 'job/job_list.html', context )

def job_detail( request , slug ) : 
    data = Job.objects.get( slug = slug ) 
    if request.method == 'POST' : 
        form = Apply_form( request.POST , request.FILES ) 
        if form.is_valid() : 
            my_form = form.save( commit = False )
            my_form.job = data
            my_form.save()  
    else : 
        form = Apply_form() 

    context = {
        'job' : data ,
        'form' : form ,

    }

    return render( request , 'job/job_detial.html' , context ) 

@login_required 
def add_job( request ) :    
    if request.method == 'POST' :
        form = Add_job( request.POST , request.FILES )
        if form.is_valid() : 
           myform = form.save( commit = False )
           myform.owner = request.user
           myform.save()
           return redirect(reverse('job:job_list')) 


    else : 
        form = Add_job() 
    return render( request , 'job/add_job.html' , { 'form' : form } )

accounts/templates/accounts/profile.html
<ul>
    <li>{{profile}}</li>
    <li>{{profile.user.email}}</li>
    <li>{{profile.phone_number}}</li>
    <li>{{profile.city}}</li>
    <a href=" {% url 'accounts:profile_edit' %} "> Edit profile </a>
</ul>

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}


<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <!-- header-end -->

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
 
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>edit profile</h4>
                        <form action="#" method="post" enctype= "multipart/form-data" >
                            {% csrf_token %}
                            {% bootstrap_form userform %}
                            {% bootstrap_form profileform %}
                            {% buttons %}

                                <button type="submit" class="boxed-btn3 w-100"> edit now </button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>y
                    {% endblock body %}
</body>

</html>

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}


<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <!-- header-end -->

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3> add job </h3>
                   </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>post new job</h4>
                        <form action="#" method="post" enctype= "multipart/form-data" >
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            {% buttons %}

                                <button type="submit" class="boxed-btn3 w-100"> applay now </button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>y
                    {% endblock body %}
</body>

</html>

templates/base.html
{% load static %} 
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css'%}">

    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
<header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="index.html">home</a></li>
                                            <li><a href="{% url 'job:job_list' %}">Browse Job</a></li>
                                            <li><a href="#">pages <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="candidate.html">Candidates </a></li>
                                                    <li><a href="job_details.html">job details </a></li>
                                                    <li><a href="elements.html">elements</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">blog <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="blog.html">blog</a></li>
                                                    <li><a href="single-blog.html">single-blog</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="{% url 'contact:contact'%}">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                                <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                            {% if request.user.is_authenticated %}
                                   <div class="phone_num d-none d-xl-block">
                                     <a href="{% url 'accounts:profile' %}">profile</a>
                                    </div>
                            {% else %}
                                    <div class="phone_num d-none d-xl-block">
                                     <a href="{% url 'login' %}">Log in</a>
                                    </div>
                            {% endif %}
      

                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="{% url 'job:add_job' %}">Post a Job</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->
     {% block body %}

     {% endblock body %}

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>
                            <p>
                                finloan@support.com <br>
                                +10 873 672 6782 <br>
                                600/D, Green road, NewYork
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                                luckily.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js'%}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js'%}"></script>
    <script src="{% static 'js/ajax-form.js'%}"></script>
    <script src="{% static 'js/waypoints.min.js'%}"></script>
    <script src="{% static 'js/jquery.counterup.min.js'%}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js'%}"></script>
    <script src="{% static 'js/scrollIt.js'%}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js'%}"></script>
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/nice-select.min.js'%}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'js/plugins.js'%}"></script>
    <script src="{% static 'js/gijgo.min.js'%}"></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js'%}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js'%}"></script>
    <script src="{% static 'js/jquery.form.js'%}"></script>
    <script src="{% static 'js/jquery.validate.min.js'%}"></script>
    <script src="{% static 'js/mail-script.js'%}"></script>


    <script src="{% static 'js/main.js'%}"></script>
</body>

</html>

templates/base_generic.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}


<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <!-- header-end -->

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                   </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10">

                    <div class="apply_job_form white-bg"  >
                     {% block content %}
                    
                    {% endblock content %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

                    {% endblock body %}
</body>

</html>